### PR TITLE
Adds latest episode

### PR DESCRIPTION
**Pull request by roblevintennis**
@Ihatetomatoes I tried to run `gatsby build` and it just sort of hangs:

image

Was gonna deploy too but might be an issue I'm not understanding there. I'll leave it for a few more minutes

### CODE REVIEW

**Comment by Ihatetomatoes** [comment]
Not sure what the issue was. I did merge your pull request and everything
worked fine for me.

The only thing I changed is the url of the MP3 file was http:// so I made
it *https://*

BTW:

To run the site locally run: *gatsby develop*
To deploy your code to the life github page run: *npm run deploy*

Thanks for doing the notes for this episode.

Cheers
Petr

**Comment by roblevintennis** [comment]
Hrm, interesting, ok well glad it worked and note taken on the https for future! Yeah, I've been running `gatsby develop` to preview which works, but  I thought I needed to get `gatsby build` to complete before running the deploy no?

**Comment by Ihatetomatoes** [comment]
It will build as part of the deploy also.

**Comment by roblevintennis** [comment]
ah ok, good to know for next time around .. thanks. 👍

**Pull request merged**
